"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Maximize } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DEMO_VIDEO_SRC } from "@/lib/report-config";
import { Positioning, Decisions, Mechanism } from "@/components/report-stories";
const REPO = "https://github.com/allenchenhan99/entente";
const chapters = ["定位", "問題與取捨", "如何運作", "Demo", "證據與邊界", "下一步"];
const times = ["00:25", "01:05", "00:40", "02:00", "00:30", "00:20"];
function Source({ href, children }: { href: string; children: React.ReactNode }) { return <a className="source-link" href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={14} /></a>; }
function Kicker({ children }: { children: React.ReactNode }) { return <p className="kicker">{children}</p>; }
function Demo() {
  const [error, setError] = useState(false);
  return <div className="demo-slide"><div className="demo-heading"><div><Kicker>SEE IT WORK / 一次完整交付</Kicker><h2>從任務，走到<span>證據。</span></h2></div><span className="duration">ONE DEMO <b>≤ 02:00</b></span></div><div className="video-stage">{DEMO_VIDEO_SRC && !error ? <video controls preload="metadata" playsInline src={DEMO_VIDEO_SRC} onError={() => setError(true)} aria-label="Entente Demo 影片">您的瀏覽器不支援影片播放。</video> : <div className="video-placeholder"><div className="video-mark"><img src="./logo.png" alt="" /></div><p>{error ? "影片暫時無法載入" : "Demo 影片待置入"}</p><span>{error ? "請稍後再試，或繼續閱讀報告。" : "保留一支影片，最長兩分鐘"}</span><div className="placeholder-timeline"><i /><span>00:00</span><span>02:00</span></div></div>}</div><div className="demo-beats"><span><b>01</b>提出任務與澄清</span><span><b>02</b>契約與 Agent 協作</span><span><b>03</b>檢查、修復、完成</span></div></div>;
}
function Evidence() {
  return <div className="standard-slide"><Kicker>PROOF & BOUNDARIES / 證據與邊界</Kicker><h2>自述不是結論。<br /><span>事件裡，看得到差異。</span></h2><div className="evidence-layout"><div className="receipt"><div className="receipt-header"><span>RECORDED RUN / LIVE-7</span><span className="live-tag">JSONL</span></div><div className="receipt-event"><code>35</code><div><span className="fail-text">check_failed</span><p>AC-3：範圍檢查失敗</p></div></div><div className="receipt-event"><code>36</code><div><span>evidence_recorded</span><p>自述與檢查不符：AC-3</p></div></div><div className="receipt-event"><code>37</code><div><span>repair_requested</span><p>針對 AC-3 提出修正要求</p></div></div><div className="receipt-event"><code>55</code><div><span className="pass-text">mission_verified</span><p>後續修復與驗證通過</p></div></div><Source href={`${REPO}/blob/46d3fcf/fixtures/events-live-7.jsonl`}>查看原始紀錄</Source></div><div className="capabilities"><div><span className="status-label implemented">已實作</span><h3>先讓交付可以被檢查。</h3><p>契約與 lint、relayd 檢查、局部修復、事件重播，以及原生 Relay Terminal。</p></div><div><span className="status-label proposed">下一步 / 提案</span><h3>再讓交付依據跨任務延續。</h3><p>版本化 context checkpoint 與交付 Passport：保留脈絡、來源、版本及驗證條件。</p><Source href={`${REPO}/issues/4`}>Context 設計討論</Source></div></div></div><p className="small-note evidence-note">這段紀錄證明檢查與修復流程可追查；不代表完整 Provenance assurance 已完成。</p></div>;
}
function Closing() { return <div className="closing-slide"><Kicker>ENTENTE / PROVENANCE ENGINEERING</Kicker><div className="closing-logo"><img src="./logo.png" alt="Entente LOGO" /></div><h2>讓 Agent 團隊交付的，<br />不只有程式碼，<br />還有<span>相信它的依據。</span></h2><p className="lead">從可驗證的契約，走向可追溯的交付鏈。</p><div className="closing-links"><a href={REPO} target="_blank" rel="noreferrer">探索專案與參與貢獻<ArrowUpRight size={20} /></a><span>Open source · MIT</span></div></div>; }
export default function Home() {
  const [slide, setSlide] = useState(0);
  const [fullscreenMessage, setFullscreenMessage] = useState("");
  const contentRef = useRef<HTMLElement>(null);
  const go = useCallback((next: number) => { const n = Math.max(0, Math.min(5, next)); setSlide(n); window.history.replaceState(null, "", `#slide-${n + 1}`); contentRef.current?.scrollTo({ top: 0 }); }, []);
  useEffect(() => { const sync = () => { const match = window.location.hash.match(/^#slide-([1-6])$/); if (match) setSlide(Number(match[1]) - 1); }; sync(); window.addEventListener("hashchange", sync); return () => window.removeEventListener("hashchange", sync); }, []);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.altKey || event.ctrlKey || event.metaKey || (event.target as HTMLElement)?.closest("button, a, input, textarea, video, [contenteditable]")) return; if (["ArrowRight", "PageDown", " "].includes(event.key)) { event.preventDefault(); go(slide + 1); } if (["ArrowLeft", "PageUp"].includes(event.key)) { event.preventDefault(); go(slide - 1); } if (event.key === "Home") go(0); if (event.key === "End") go(5); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [slide, go]);
  const fullscreen = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen(); } catch { setFullscreenMessage("此瀏覽器無法進入全螢幕，可使用瀏覽器的全螢幕功能。"); } };
  return <div className="report-shell dark"><a className="skip-link" href="#report-content">跳到報告內容</a><header className="topbar"><a href="#slide-1" onClick={() => go(0)} className="brand"><img src="./logo.png" alt="" /><span>entente<span className="brand-dot">.</span></span></a><div className="edition">HACKATHON 2026<span>PROVENANCE ENGINEERING</span></div><div className="top-actions"><Source href={REPO}>GitHub</Source><Button variant="ghost" size="icon" onClick={fullscreen} aria-label="切換全螢幕" title="全螢幕"><Maximize /></Button></div></header><main id="report-content" ref={contentRef} className="slide-viewport" tabIndex={-1}><section key={slide} className={`slide slide-${slide + 1}`} aria-label={`第 ${slide + 1} 頁：${chapters[slide]}`}>{[<Positioning key="position" />, <Decisions key="decisions" />, <Mechanism key="mechanism" />, <Demo key="demo" />, <Evidence key="evidence" />, <Closing key="closing" />][slide]}</section></main><footer className="deck-footer"><div className="slide-counter"><b>{String(slide + 1).padStart(2, "0")}</b><span>/ 06</span></div><nav aria-label="報告章節">{chapters.map((chapter, i) => <button key={chapter} className={slide === i ? "active" : ""} onClick={() => go(i)} aria-current={slide === i ? "step" : undefined}><span className="nav-dot" /><span>{chapter}</span></button>)}</nav><div className="nav-controls"><span className="pace">{times[slide]}</span><Button variant="outline" size="icon" disabled={slide === 0} onClick={() => go(slide - 1)} aria-label="上一頁"><ArrowLeft /></Button><Button variant="default" size="icon" disabled={slide === 5} onClick={() => go(slide + 1)} aria-label="下一頁"><ArrowRight /></Button></div></footer><span className="sr-only" aria-live="polite">第 {slide + 1} 頁，共 6 頁。{chapters[slide]}。{fullscreenMessage}</span></div>;
}
